export const LangKeys = {
  Commands: {
    Dev: {
      Info: 'data.displayEmbeds.devInfo',
      NotDeveloper: 'data.validationEmbeds.devOnly',
      StartupInProcess: 'data.errorEmbeds.startupInProcess',
    },
    Help: {
      ContactSupport: 'data.displayEmbeds.helpContactSupport',
      Commands: 'data.displayEmbeds.helpCommands',
    },
    Info: {
      About: 'data.displayEmbeds.about',
      Translate: 'data.displayEmbeds.translate',
      TranslatorList: 'meta.translators',
    },
    Test: {
      Test: 'data.displayEmbeds.test',
    },
    New: {
      CreateSuccessChannel: 'messages.newSeason.createSuccessChannel',
      ErrorMinMaxPlayers: 'messages.newSeason.errorMinMaxPlayers',
      ErrorCreatorNotFound: 'messages.newSeason.errorCreatorNotFound',
      ErrorPlayerCreateFailed: 'messages.newSeason.errorPlayerCreateFailed',
      ErrorDb: 'messages.newSeason.errorDatabase',
      ErrorUnknownService: 'messages.newSeason.errorUnknownService',
      ErrorGenericService: 'messages.newSeason.errorGenericService',
      ErrorUnknown: 'messages.newSeason.errorUnknown',
      ErrorUnknownSubcommand: 'messages.newCommand.errorUnknownSubcommand',
      CriticalError: 'messages.common.errorCriticalCommand',
      SeasonActivateSuccess: 'messages.newSeason.seasonActivateSuccess',
    },
    JoinSeason: {
      playerNotFound: 'messages.joinSeason.playerNotFound',
      seasonNotFound: 'messages.joinSeason.seasonNotFound',
      notOpen: 'messages.joinSeason.notOpen',
      full: 'messages.joinSeason.full',
      alreadyJoined: 'messages.joinSeason.alreadyJoined',
      success: 'messages.joinSeason.success',
      genericError: 'messages.joinSeason.genericError',
    },
    Status: {
      seasonNotFound: 'messages.status.seasonNotFound',
      seasonStatus: 'data.displayEmbeds.seasonStatus',
      genericError: 'messages.status.genericError',
    },
    Admin: {
      NotAdmin: 'data.validationEmbeds.adminOnly',
      TerminateSeasonSuccess: 'messages.admin.terminateSeasonSuccess',
      TerminateSeasonErrorNotFound: 'messages.admin.terminateSeasonErrorNotFound',
      TerminateSeasonErrorAlreadyTerminated: 'messages.admin.terminateSeasonErrorAlreadyTerminated',
      TerminateSeasonErrorDatabase: 'messages.admin.terminateSeasonErrorDatabase',
      TerminateSeasonErrorUnknown: 'messages.admin.terminateSeasonErrorUnknown',
      ListSeasonsSuccess: 'data.displayEmbeds.admin.listSeasonsSuccess',
      ListSeasonsError: 'messages.admin.listSeasonsError',
      ListPlayersSuccess: 'data.displayEmbeds.admin.listPlayersSuccess',
      ListPlayersError: 'messages.admin.listPlayersError',
      PlayerBanSuccess: 'messages.admin.playerBanSuccess',
      PlayerBanError: 'messages.admin.playerBanError',
      PlayerBanNotFound: 'messages.admin.playerBanNotFound',
      PlayerBanAlreadyBanned: 'messages.admin.playerBanAlreadyBanned',
      PlayerUnbanSuccess: 'messages.admin.playerUnbanSuccess',
      PlayerUnbanError: 'messages.admin.playerUnbanError',
      PlayerUnbanNotFound: 'messages.admin.playerUnbanNotFound',
      PlayerUnbanNotBanned: 'messages.admin.playerUnbanNotBanned',
    },
    Config: {
      ViewSuccess: 'data.displayEmbeds.config.viewSuccess',
      UpdateSuccess: 'messages.config.updateSuccess',
      ValidationError: 'messages.config.validationError',
      DatabaseError: 'messages.config.databaseError',
      UnknownError: 'messages.config.unknownError',
      NoUpdatesProvided: 'messages.config.noUpdatesProvided',
      NotAdmin: 'data.validationEmbeds.adminOnly',
    },
    // Add other commands here in the future
  },
  Game: {
    SeasonCompletion: 'data.displayEmbeds.seasonCompletion',
    SeasonId: 'messages.game.seasonId',
  },
  Turn: {
    NewTurnAvailable: 'messages.turnOffer.newTurnAvailable',
    SubmissionTimeoutSkipped: 'messages.turnTimeout.submissionTimeoutSkipped',
  },
  Ready: {
    PlayerNotFound: 'messages.ready.playerNotFound',
    NoOfferedTurns: 'messages.ready.noOfferedTurns',
    AlreadyHasPendingTurn: 'messages.ready.alreadyHasPendingTurn',
    ClaimFailed: 'messages.ready.claimFailed',
    ClaimSuccess: 'messages.ready.claimSuccess',
  },
  Submission: {
    PlayerNotFound: 'messages.submission.playerNotFound',
    NoPendingTurns: 'messages.submission.noPendingTurns',
    NoAttachmentFound: 'messages.submission.noAttachmentFound',
    InvalidFileType: 'messages.submission.invalidFileType',
    NoContentFound: 'messages.submission.noContentFound',
    WrongContentType: 'messages.submission.wrongContentType',
    SubmitFailed: 'messages.submission.submitFailed',
    SubmitSuccess: 'messages.submission.submitSuccess',
  },
} as const; 