import { SeasonConfig } from '@prisma/client';
import { ActionRowBuilder, ModalBuilder, TextInputBuilder, TextInputStyle } from 'discord.js';

/**
 * Generates an auto-generated season name based on current date
 * @returns A formatted season name like "Season 2024-01-15" or "Winter 2024"
 */
export function generateAutoSeasonName(): string {
    const now = new Date();
    const year = now.getFullYear();
    const month = now.getMonth() + 1; // 0-indexed, so add 1
    const day = now.getDate();
    
    // Generate a simple date-based name
    const dateStr = `${year}-${month.toString().padStart(2, '0')}-${day.toString().padStart(2, '0')}`;
    return `Season ${dateStr}`;
}

/**
 * Creates the first step modal for season creation with prefilled default values
 * @param defaults Optional default configuration values to prefill the modal
 * @param autoGeneratedName Optional auto-generated season name
 */
export function createSeasonCreationStep1Modal(defaults?: SeasonConfig, autoGeneratedName?: string): ModalBuilder {
    const modal = new ModalBuilder()
        .setCustomId('season_create_step1')
        .setTitle('Create New Season - Basic Settings');

    // Season Name input (now with auto-generated default)
    const seasonNameInput = new TextInputBuilder()
        .setCustomId('seasonNameInput')
        .setLabel('Season Name (optional)')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., Winter 2024')
        .setRequired(false)
        .setMaxLength(50);
    
    if (autoGeneratedName) {
        seasonNameInput.setValue(autoGeneratedName);
    }

    // Min Players input (prefilled with defaults)
    const minPlayersInput = new TextInputBuilder()
        .setCustomId('minPlayersInput')
        .setLabel('Minimum Players')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 2')
        .setRequired(true)
        .setMinLength(1)
        .setMaxLength(2);
    
    if (defaults?.minPlayers) {
        minPlayersInput.setValue(defaults.minPlayers.toString());
    }

    // Max Players input (prefilled with defaults)
    const maxPlayersInput = new TextInputBuilder()
        .setCustomId('maxPlayersInput')
        .setLabel('Maximum Players')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 8')
        .setRequired(true)
        .setMinLength(1)
        .setMaxLength(2);
    
    if (defaults?.maxPlayers) {
        maxPlayersInput.setValue(defaults.maxPlayers.toString());
    }

    // Open Duration input (prefilled with defaults)
    const openDurationInput = new TextInputBuilder()
        .setCustomId('openDurationInput')
        .setLabel('Open Duration (optional)')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 7d, 24h')
        .setRequired(false)
        .setMaxLength(10);
    
    if (defaults?.openDuration) {
        openDurationInput.setValue(defaults.openDuration);
    }

    // Claim Timeout input (NEW - prefilled with defaults)
    const claimTimeoutInput = new TextInputBuilder()
        .setCustomId('claimTimeoutInput')
        .setLabel('Claim Timeout (optional)')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 1d, 12h')
        .setRequired(false)
        .setMaxLength(10);
    
    if (defaults?.claimTimeout) {
        claimTimeoutInput.setValue(defaults.claimTimeout);
    }

    // Create action rows (Discord allows max 5 components per modal)
    const firstRow = new ActionRowBuilder<TextInputBuilder>().addComponents(seasonNameInput);
    const secondRow = new ActionRowBuilder<TextInputBuilder>().addComponents(minPlayersInput);
    const thirdRow = new ActionRowBuilder<TextInputBuilder>().addComponents(maxPlayersInput);
    const fourthRow = new ActionRowBuilder<TextInputBuilder>().addComponents(openDurationInput);
    const fifthRow = new ActionRowBuilder<TextInputBuilder>().addComponents(claimTimeoutInput);

    modal.addComponents(firstRow, secondRow, thirdRow, fourthRow, fifthRow);

    return modal;
}

/**
 * Creates the first step modal for admin season configuration with basic settings
 * @param currentConfig Current season configuration values to prefill the modal
 */
export function createAdminSeasonConfigModal(currentConfig?: any): ModalBuilder {
    const modal = new ModalBuilder()
        .setCustomId('admin_season_config_step1')
        .setTitle('Season Configuration - Basic Settings');

    // Claim Timeout input
    const claimTimeoutInput = new TextInputBuilder()
        .setCustomId('claimTimeoutInput')
        .setLabel('Claim Timeout')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 1d, 12h')
        .setRequired(true)
        .setMaxLength(10);
    
    if (currentConfig?.claimTimeout) {
        claimTimeoutInput.setValue(currentConfig.claimTimeout);
    }

    // Writing Timeout input
    const writingTimeoutInput = new TextInputBuilder()
        .setCustomId('writingTimeoutInput')
        .setLabel('Writing Timeout')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 1d, 8h')
        .setRequired(true)
        .setMaxLength(10);
    
    if (currentConfig?.writingTimeout) {
        writingTimeoutInput.setValue(currentConfig.writingTimeout);
    }

    // Drawing Timeout input
    const drawingTimeoutInput = new TextInputBuilder()
        .setCustomId('drawingTimeoutInput')
        .setLabel('Drawing Timeout')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 1d, 1h')
        .setRequired(true)
        .setMaxLength(10);
    
    if (currentConfig?.drawingTimeout) {
        drawingTimeoutInput.setValue(currentConfig.drawingTimeout);
    }

    // Min Players input
    const minPlayersInput = new TextInputBuilder()
        .setCustomId('minPlayersInput')
        .setLabel('Min Players')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 6')
        .setRequired(true)
        .setMaxLength(3);
    
    if (currentConfig?.minPlayers) {
        minPlayersInput.setValue(currentConfig.minPlayers.toString());
    }

    // Max Players input
    const maxPlayersInput = new TextInputBuilder()
        .setCustomId('maxPlayersInput')
        .setLabel('Max Players')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 20')
        .setRequired(true)
        .setMaxLength(3);
    
    if (currentConfig?.maxPlayers) {
        maxPlayersInput.setValue(currentConfig.maxPlayers.toString());
    }

    // Create action rows (Discord allows max 5 components per modal)
    const firstRow = new ActionRowBuilder<TextInputBuilder>().addComponents(claimTimeoutInput);
    const secondRow = new ActionRowBuilder<TextInputBuilder>().addComponents(writingTimeoutInput);
    const thirdRow = new ActionRowBuilder<TextInputBuilder>().addComponents(drawingTimeoutInput);
    const fourthRow = new ActionRowBuilder<TextInputBuilder>().addComponents(minPlayersInput);
    const fifthRow = new ActionRowBuilder<TextInputBuilder>().addComponents(maxPlayersInput);

    modal.addComponents(firstRow, secondRow, thirdRow, fourthRow, fifthRow);

    return modal;
}

/**
 * Creates the second step modal for admin season configuration with advanced settings
 * @param currentConfig Current season configuration values to prefill the modal
 */
export function createAdminSeasonConfigStep2Modal(currentConfig?: any): ModalBuilder {
    const modal = new ModalBuilder()
        .setCustomId('admin_season_config_step2')
        .setTitle('Season Configuration - Advanced Settings');

    // Turn Pattern input
    const turnPatternInput = new TextInputBuilder()
        .setCustomId('turnPatternInput')
        .setLabel('Turn Pattern')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., writing,drawing')
        .setRequired(true)
        .setMaxLength(50);
    
    if (currentConfig?.turnPattern) {
        turnPatternInput.setValue(currentConfig.turnPattern);
    }

    // Open Duration input
    const openDurationInput = new TextInputBuilder()
        .setCustomId('openDurationInput')
        .setLabel('Open Duration')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 7d, 3d')
        .setRequired(true)
        .setMaxLength(10);
    
    if (currentConfig?.openDuration) {
        openDurationInput.setValue(currentConfig.openDuration);
    }

    // Claim Warning input
    const claimWarningInput = new TextInputBuilder()
        .setCustomId('claimWarningInput')
        .setLabel('Claim Warning')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 1h, 30m')
        .setRequired(true)
        .setMaxLength(10);
    
    if (currentConfig?.claimWarning) {
        claimWarningInput.setValue(currentConfig.claimWarning);
    }

    // Writing Warning input
    const writingWarningInput = new TextInputBuilder()
        .setCustomId('writingWarningInput')
        .setLabel('Writing Warning')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 1m, 30s')
        .setRequired(true)
        .setMaxLength(10);
    
    if (currentConfig?.writingWarning) {
        writingWarningInput.setValue(currentConfig.writingWarning);
    }

    // Drawing Warning input
    const drawingWarningInput = new TextInputBuilder()
        .setCustomId('drawingWarningInput')
        .setLabel('Drawing Warning')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 10m, 5m')
        .setRequired(true)
        .setMaxLength(10);
    
    if (currentConfig?.drawingWarning) {
        drawingWarningInput.setValue(currentConfig.drawingWarning);
    }

    // Create action rows (Discord allows max 5 components per modal)
    const firstRow = new ActionRowBuilder<TextInputBuilder>().addComponents(turnPatternInput);
    const secondRow = new ActionRowBuilder<TextInputBuilder>().addComponents(openDurationInput);
    const thirdRow = new ActionRowBuilder<TextInputBuilder>().addComponents(claimWarningInput);
    const fourthRow = new ActionRowBuilder<TextInputBuilder>().addComponents(writingWarningInput);
    const fifthRow = new ActionRowBuilder<TextInputBuilder>().addComponents(drawingWarningInput);

    modal.addComponents(firstRow, secondRow, thirdRow, fourthRow, fifthRow);

    return modal;
}

/**
 * Creates the first step modal for admin game configuration with basic settings
 * @param currentConfig Current game configuration values to prefill the modal
 */
export function createAdminGameConfigModal(currentConfig?: any): ModalBuilder {
    const modal = new ModalBuilder()
        .setCustomId('admin_game_config_step1')
        .setTitle('Game Configuration - Basic Settings');

    // Writing Timeout input
    const writingTimeoutInput = new TextInputBuilder()
        .setCustomId('writingTimeoutInput')
        .setLabel('Writing Timeout')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 5m, 1h')
        .setRequired(true)
        .setMaxLength(10);
    
    if (currentConfig?.writingTimeout) {
        writingTimeoutInput.setValue(currentConfig.writingTimeout);
    }

    // Drawing Timeout input
    const drawingTimeoutInput = new TextInputBuilder()
        .setCustomId('drawingTimeoutInput')
        .setLabel('Drawing Timeout')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 20m, 1h')
        .setRequired(true)
        .setMaxLength(10);
    
    if (currentConfig?.drawingTimeout) {
        drawingTimeoutInput.setValue(currentConfig.drawingTimeout);
    }

    // Stale Timeout input
    const staleTimeoutInput = new TextInputBuilder()
        .setCustomId('staleTimeoutInput')
        .setLabel('Stale Timeout')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 3d, 1w')
        .setRequired(true)
        .setMaxLength(10);
    
    if (currentConfig?.staleTimeout) {
        staleTimeoutInput.setValue(currentConfig.staleTimeout);
    }

    // Min Turns input
    const minTurnsInput = new TextInputBuilder()
        .setCustomId('minTurnsInput')
        .setLabel('Min Turns')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 6')
        .setRequired(true)
        .setMaxLength(3);
    
    if (currentConfig?.minTurns) {
        minTurnsInput.setValue(currentConfig.minTurns.toString());
    }

    // Max Turns input
    const maxTurnsInput = new TextInputBuilder()
        .setCustomId('maxTurnsInput')
        .setLabel('Max Turns (optional)')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 12 (leave empty for unlimited)')
        .setRequired(false)
        .setMaxLength(3);
    
    if (currentConfig?.maxTurns) {
        maxTurnsInput.setValue(currentConfig.maxTurns.toString());
    }

    // Create action rows (Discord allows max 5 components per modal)
    const firstRow = new ActionRowBuilder<TextInputBuilder>().addComponents(writingTimeoutInput);
    const secondRow = new ActionRowBuilder<TextInputBuilder>().addComponents(drawingTimeoutInput);
    const thirdRow = new ActionRowBuilder<TextInputBuilder>().addComponents(staleTimeoutInput);
    const fourthRow = new ActionRowBuilder<TextInputBuilder>().addComponents(minTurnsInput);
    const fifthRow = new ActionRowBuilder<TextInputBuilder>().addComponents(maxTurnsInput);

    modal.addComponents(firstRow, secondRow, thirdRow, fourthRow, fifthRow);

    return modal;
}

/**
 * Creates the second step modal for admin game configuration with advanced settings
 * @param currentConfig Current game configuration values to prefill the modal
 */
export function createAdminGameConfigStep2Modal(currentConfig?: any): ModalBuilder {
    const modal = new ModalBuilder()
        .setCustomId('admin_game_config_step2')
        .setTitle('Game Configuration - Advanced Settings');

    // Writing Warning input
    const writingWarningInput = new TextInputBuilder()
        .setCustomId('writingWarningInput')
        .setLabel('Writing Warning')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 1m, 30s')
        .setRequired(true)
        .setMaxLength(10);
    
    if (currentConfig?.writingWarning) {
        writingWarningInput.setValue(currentConfig.writingWarning);
    }

    // Drawing Warning input
    const drawingWarningInput = new TextInputBuilder()
        .setCustomId('drawingWarningInput')
        .setLabel('Drawing Warning')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 2m, 5m')
        .setRequired(true)
        .setMaxLength(10);
    
    if (currentConfig?.drawingWarning) {
        drawingWarningInput.setValue(currentConfig.drawingWarning);
    }

    // Return Count input
    const returnCountInput = new TextInputBuilder()
        .setCustomId('returnCountInput')
        .setLabel('Return Count (optional)')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 0, 2 (0 = no returns allowed)')
        .setRequired(false)
        .setMaxLength(2);
    
    if (currentConfig?.returnCount !== null && currentConfig?.returnCount !== undefined) {
        returnCountInput.setValue(currentConfig.returnCount.toString());
    }

    // Return Cooldown input
    const returnCooldownInput = new TextInputBuilder()
        .setCustomId('returnCooldownInput')
        .setLabel('Return Cooldown (optional)')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 3 (turns between returns)')
        .setRequired(false)
        .setMaxLength(2);
    
    if (currentConfig?.returnCooldown !== null && currentConfig?.returnCooldown !== undefined) {
        returnCooldownInput.setValue(currentConfig.returnCooldown.toString());
    }

    // Turn Pattern input
    const turnPatternInput = new TextInputBuilder()
        .setCustomId('turnPatternInput')
        .setLabel('Turn Pattern')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., writing,drawing')
        .setRequired(true)
        .setMaxLength(50);
    
    if (currentConfig?.turnPattern) {
        turnPatternInput.setValue(currentConfig.turnPattern);
    }

    // Create action rows (Discord allows max 5 components per modal)
    const firstRow = new ActionRowBuilder<TextInputBuilder>().addComponents(writingWarningInput);
    const secondRow = new ActionRowBuilder<TextInputBuilder>().addComponents(drawingWarningInput);
    const thirdRow = new ActionRowBuilder<TextInputBuilder>().addComponents(returnCountInput);
    const fourthRow = new ActionRowBuilder<TextInputBuilder>().addComponents(returnCooldownInput);
    const fifthRow = new ActionRowBuilder<TextInputBuilder>().addComponents(turnPatternInput);

    modal.addComponents(firstRow, secondRow, thirdRow, fourthRow, fifthRow);

    return modal;
}

 