import { SeasonConfig } from '@prisma/client';
import { ActionRowBuilder, ModalBuilder, TextInputBuilder, TextInputStyle } from 'discord.js';

/**
 * Generates an auto-generated season name based on current date
 * @returns A formatted season name like "Season 2024-01-15" or "Winter 2024"
 */
export function generateAutoSeasonName(): string {
    const now = new Date();
    const year = now.getFullYear();
    const month = now.getMonth() + 1; // 0-indexed, so add 1
    const day = now.getDate();
    
    // Generate a simple date-based name
    const dateStr = `${year}-${month.toString().padStart(2, '0')}-${day.toString().padStart(2, '0')}`;
    return `Season ${dateStr}`;
}

/**
 * Creates the first step modal for season creation with prefilled default values
 * @param defaults Optional default configuration values to prefill the modal
 * @param autoGeneratedName Optional auto-generated season name
 */
export function createSeasonCreationStep1Modal(defaults?: SeasonConfig, autoGeneratedName?: string): ModalBuilder {
    const modal = new ModalBuilder()
        .setCustomId('season_create_step1')
        .setTitle('Create New Season - Basic Settings');

    // Season Name input (now with auto-generated default)
    const seasonNameInput = new TextInputBuilder()
        .setCustomId('seasonNameInput')
        .setLabel('Season Name (optional)')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., Winter 2024')
        .setRequired(false)
        .setMaxLength(50);
    
    if (autoGeneratedName) {
        seasonNameInput.setValue(autoGeneratedName);
    }

    // Min Players input (prefilled with defaults)
    const minPlayersInput = new TextInputBuilder()
        .setCustomId('minPlayersInput')
        .setLabel('Minimum Players')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 2')
        .setRequired(true)
        .setMinLength(1)
        .setMaxLength(2);
    
    if (defaults?.minPlayers) {
        minPlayersInput.setValue(defaults.minPlayers.toString());
    }

    // Max Players input (prefilled with defaults)
    const maxPlayersInput = new TextInputBuilder()
        .setCustomId('maxPlayersInput')
        .setLabel('Maximum Players')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 8')
        .setRequired(true)
        .setMinLength(1)
        .setMaxLength(2);
    
    if (defaults?.maxPlayers) {
        maxPlayersInput.setValue(defaults.maxPlayers.toString());
    }

    // Open Duration input (prefilled with defaults)
    const openDurationInput = new TextInputBuilder()
        .setCustomId('openDurationInput')
        .setLabel('Open Duration (optional)')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 7d, 24h')
        .setRequired(false)
        .setMaxLength(10);
    
    if (defaults?.openDuration) {
        openDurationInput.setValue(defaults.openDuration);
    }

    // Claim Timeout input (NEW - prefilled with defaults)
    const claimTimeoutInput = new TextInputBuilder()
        .setCustomId('claimTimeoutInput')
        .setLabel('Claim Timeout (optional)')
        .setStyle(TextInputStyle.Short)
        .setPlaceholder('e.g., 1d, 12h')
        .setRequired(false)
        .setMaxLength(10);
    
    if (defaults?.claimTimeout) {
        claimTimeoutInput.setValue(defaults.claimTimeout);
    }

    // Create action rows (Discord allows max 5 components per modal)
    const firstRow = new ActionRowBuilder<TextInputBuilder>().addComponents(seasonNameInput);
    const secondRow = new ActionRowBuilder<TextInputBuilder>().addComponents(minPlayersInput);
    const thirdRow = new ActionRowBuilder<TextInputBuilder>().addComponents(maxPlayersInput);
    const fourthRow = new ActionRowBuilder<TextInputBuilder>().addComponents(openDurationInput);
    const fifthRow = new ActionRowBuilder<TextInputBuilder>().addComponents(claimTimeoutInput);

    modal.addComponents(firstRow, secondRow, thirdRow, fourthRow, fifthRow);

    return modal;
} 